# Generated by Django 4.1.7 on 2023-05-08 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('idea', models.CharField(blank=True, max_length=255)),
                ('expected_result', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'TestCases',
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'TestSuites',
            },
        ),
        migrations.CreateModel(
            name='TestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField()),
                ('action', models.CharField(max_length=255)),
                ('expected_result', models.CharField(blank=True, max_length=255)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios_api.testcase')),
            ],
            options={
                'verbose_name_plural': 'TestSteps',
            },
        ),
    ]
