# Generated by Django 4.1.7 on 2023-05-08 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='workitem',
            field=models.SmallIntegerField(default='2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsuite',
            name='workitem',
            field=models.SmallIntegerField(default='2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testcase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
