# Generated by Django 4.1.7 on 2023-05-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios_api', '0002_testcase_created_testcase_workitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='workitem',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='workitem',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
