# Generated by Django 4.1.7 on 2023-06-09 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios_api', '0002_testcase_created_testcase_workitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractTestSuite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestPlanContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('can_edit', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=True)),
                ('can_progress', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='workitem',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='workitem',
        ),
        migrations.AddField(
            model_name='testcase',
            name='step',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='suite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scenarios_api.testsuite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsuite',
            name='version',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_result',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='abstract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scenarios_api.abstracttestsuite'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='testcase',
            constraint=models.UniqueConstraint(fields=('suite', 'step'), name='unique_step_for_testsuite'),
        ),
        migrations.AddConstraint(
            model_name='teststep',
            constraint=models.UniqueConstraint(fields=('test_case', 'step'), name='unique_teststep_testcase_step'),
        ),
        migrations.AddConstraint(
            model_name='testsuite',
            constraint=models.UniqueConstraint(fields=('abstract', 'version'), name='unique_testsuite_version'),
        ),
        migrations.AddField(
            model_name='testplancontent',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios_api.testplan'),
        ),
        migrations.AddField(
            model_name='testplancontent',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios_api.abstracttestsuite'),
        ),
    ]
