# Generated by Django 4.1.7 on 2023-05-08 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios_api', '0003_alter_testcase_workitem_alter_testsuite_workitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={},
        ),
        migrations.RenameField(
            model_name='testsuite',
            old_name='workitem',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='created',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='expected_result',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='idea',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='title',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='workitem',
        ),
        migrations.AlterField(
            model_name='testcase',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TestCaseSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.SmallIntegerField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('idea', models.CharField(blank=True, max_length=255)),
                ('expected_result', models.CharField(max_length=255)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios_api.testcase', unique=True)),
            ],
            options={
                'verbose_name_plural': 'TestCases',
            },
        ),
    ]
