# Generated by Django 4.1.7 on 2023-06-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios_api', '0004_remove_testsuite_unique_testsuite_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplancontent',
            name='step',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='testsuite',
            constraint=models.UniqueConstraint(fields=('abstract', 'version'), name='unique_testsuite_version'),
        ),
    ]
