# Generated by Django 4.1.7 on 2023-06-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios_api', '0006_alter_testplancontent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplancontent',
            name='version',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
