# Generated by Django 4.1.7 on 2023-05-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios_api', '0006_alter_testcase_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='tc_id',
            field=models.PositiveIntegerField(),
        ),
    ]
