# Generated by Django 4.1.7 on 2023-05-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios_api', '0007_alter_testcase_tc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='version',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='testcase',
            constraint=models.UniqueConstraint(fields=('tc_id', 'version'), name='unique_testcase_tc_id_version'),
        ),
    ]
