# Generated by Django 4.1.7 on 2023-05-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios_api', '0008_testcase_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='version',
            field=models.PositiveIntegerField(),
        ),
    ]
