# Generated by Django 4.1.7 on 2023-06-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios_api', '0009_alter_testplancontent_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'verbose_name_plural': 'Test Cases'},
        ),
        migrations.AlterModelOptions(
            name='testplan',
            options={'verbose_name_plural': 'Test Plans'},
        ),
        migrations.AlterModelOptions(
            name='testplancontent',
            options={'verbose_name_plural': 'Test Plan Contents'},
        ),
        migrations.AlterModelOptions(
            name='teststep',
            options={'verbose_name_plural': 'Test Steps'},
        ),
        migrations.AlterModelOptions(
            name='testsuite',
            options={'verbose_name_plural': 'Test Suites'},
        ),
        migrations.RenameField(
            model_name='testplancontent',
            old_name='suite',
            new_name='abstract_suite',
        ),
        migrations.AlterField(
            model_name='testplan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
