# Generated by Django 4.1.7 on 2023-06-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios_api', '0010_alter_testcase_options_alter_testplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='actionable_steps',
            field=models.TextField(blank=True),
        ),
    ]
