# Generated by Django 4.1.7 on 2023-05-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios_api', '0010_rename_tc_id_testcase_item'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='testcase',
            name='unique_testcase_tc_id_version',
        ),
        migrations.AddConstraint(
            model_name='testcase',
            constraint=models.UniqueConstraint(fields=('item', 'version'), name='unique_testcase_item_version'),
        ),
    ]
