# Generated by Django 4.1.7 on 2023-05-08 13:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios_api', '0011_remove_testcase_unique_testcase_tc_id_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='suite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scenarios_api.testsuite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsuite',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsuite',
            name='version',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='item',
            field=models.PositiveIntegerField(),
        ),
    ]
