# Generated by Django 4.1.7 on 2023-05-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios_api', '0012_testcase_suite_testsuite_created_testsuite_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuite',
            name='created',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='version',
        ),
    ]
