# Generated by Django 4.1.7 on 2023-05-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios_api', '0013_remove_testsuite_created_remove_testsuite_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('TS', 'TestSuite'), ('TC', 'TestCase')], max_length=2)),
            ],
            options={
                'verbose_name_plural': 'WorkItems',
            },
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='testcase',
            name='unique_testcase_item_version',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='item',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='suite',
        ),
    ]
