# Generated by Django 4.1.7 on 2023-05-08 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios_api', '0015_remove_workitem_id_alter_workitem_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'verbose_name_plural': 'TestCases'},
        ),
        migrations.AddField(
            model_name='testcase',
            name='workitemm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scenarios_api.workitem'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='testcase',
            constraint=models.UniqueConstraint(fields=('workitemm', 'version'), name='unique_testcase_workitem_version'),
        ),
    ]
