# Generated by Django 4.1.7 on 2023-05-08 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios_api', '0017_remove_testcase_unique_testcase_workitem_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuite',
            name='item',
        ),
        migrations.AddField(
            model_name='testsuite',
            name='workitem',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='scenarios_api.workitem'),
            preserve_default=False,
        ),
    ]
