# Generated by Django 4.1.7 on 2023-05-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios_api', '0018_remove_testsuite_item_testsuite_workitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workitem',
            old_name='code',
            new_name='id',
        ),
    ]
