# Generated by Django 4.1.7 on 2023-05-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios_api', '0019_rename_code_workitem_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='testsuite',
            constraint=models.UniqueConstraint(fields=('workitem',), name='unique_testsuite_workitem_version'),
        ),
    ]
